### ISSUE TITLE
Look for an alternative to the jwt-cpp submodule in rmf_visualzation_schedule

### ISSUE THREAD

**Issue by marcoag** [open-rmf/rmf_visualization#28]
`rmf_visualization_schedule` uses a git submodule to pull the `jwt-cpp` dependency. This dependency pull is done at compilation time on the [`CMakeLists.txt` ](https://github.com/open-rmf/rmf_visualization/blob/main/rmf_visualization_schedule/CMakeLists.txt#L15). This is not the best way to deal with dependencies and it doesn't work for packaging purposes because of many reasons. 

It seems that this package is used to check and decode a jwt token passed to the websocket server. I would suggest we try to find an Ubuntu package that provides this functionality instead. So far after a quick search I found `libjwt0` maybe it's worth a look.

**Comment by marcoag** [comment]
It seems that the new added `nlohman-json` it's not available for `rhel`:  https://pkgs.org/search/?q=nlohmann 
I am afraid we are currently not able to have a separate branch for `rhel` releases (which would be the ideal solution to this problem) therefore I suggest we go back to the previous state regarding this dependency (using the header file).

@ChawinTan can you remove the dependency and add the header back again?

**Comment by ChawinTan** [comment]
Roger that!
